### PR TITLE
feat: add float support

### LINKED ISSUE #573: Wrapping text around images.
**Is your feature request related to a problem? Please describe.**
I would like to use float to wrap text around images. Is this possible with current implementation? I don't want to use `flex-flow: row` to have image and text in one row. because I want to wrap text around an image. The text could be 10 pages long like a lot of articles in news do. 

**Describe the solution you'd like**
```js
<View>
  <Image
    src="https://avatars1.githubusercontent.com/u/5691926?s=460&v=4"
    style={{ width: 100, float: 'left' }}
  />
  <Text>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
    ut ligula ullamcorper, sodales ante dignissim, commodo lorem. In a
    egestas ex. Sed rhoncus lorem posuere massa rutrum consectetur. In
    at augue vitae risus fermentum volutpat sagittis nec ex.
  </Text>
</View>
```

**Describe alternatives you've considered**
Using `flex`, but it's not possible to wrap text under the image with it.

### PR DESCRIPTION
**Pull request by diegomura**
Fixes: https://github.com/diegomura/react-pdf/issues/573

Adds CSS float support for wrap text around elements
Almost done, seeing some pagination issue I need to check

Screen Shot 2022-06-20 at 02 59 10

### CODE REVIEW

**Comment by platon-ivanov** [comment]
Hello! Thank you for showing floating images are indeed possible! It would be great if this feature was merged with the master branch.
Is there any way we could use this in the meantime?

**Comment by dangthaii** [comment]
is this complete to merge to master?

**Comment by diegomura** [comment]
No. Wasn't able to resume this effort

**Comment by KODIKAS-NL** [comment]
> No. Wasn't able to resume this effort

Can you indicate what problems still need to be solved for this to work? I might give it a go myself.

**Comment by romadryud** [comment]
@KODIKAS-NL How I can help to deliver this pull request? @diegomura Is there any specific problems that need to be solved or just general pagination issues?

**Pull request closed without merging**
