### PR TITLE
Fix fonts loading

### LINKED ISSUE #184: Custom Font Loading Issue on Second+ Attempt
Hi React PDF,

Still love this project! I am loading in custom fonts, and on my first time viewing the PDF it works, however, if I try to open the file again, I get an error relating to my custom font: 
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: ENOENT: no such file or directory, open 'Basetica'`.

This is how I am loading the font, above the stylesheet in my main file:
```
Font.register(`${__dirname}/fonts/Basetica/Basetica-Medium.ttf`, {
  family: 'Basetica',
});
```

And the full stack trace - I wonder if it has to do with fontkit then trying to load the font? Interesting that it doesn't actually trace back to my component file:
```
{ Error: ENOENT: no such file or directory, open 'Basetica'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fontkit.openSync (/Users/lauracressman/Desktop/src/commons/node_modules/fontkit/src/base.js:15:19)
    at Function.PDFFont.open (/Users/lauracressman/Desktop/src/commons/node_modules/pdfkit/js/font.js:14:24)
    at PDFDocument.font (/Users/lauracressman/Desktop/src/commons/node_modules/pdfkit/js/mixins/fonts.js:39:28)
    at Text.setFontFamily (/Users/lauracressman/Desktop/src/commons/node_modules/@react-pdf/core/lib/elements/Text.js:94:17)
    at Text.measureText (/Users/lauracressman/Desktop/src/commons/node_modules/@react-pdf/core/lib/elements/Text.js:119:12)
    at External.data (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/dist/entry-common.js:218:40)
    at Array.eval (eval at buildJSCallerFunction (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:1449:328), <anonymous>:1:86)
    at Array.ASM_CONSTS (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:557:45)
    at _emscripten_asm_const_iiididi (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:565:28)
    at Tg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3475:134)
    at Rg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3471:64)
    at Qg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3468:144)
    at Array.Pg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3462:44)
```

Thanks!

Sincerely,
Laura

### PR DESCRIPTION
**Pull request by diegomura**
Fixes #184

### CODE REVIEW

**Comment by flaurida** [comment]
What should I do to address this issue? Load the fonts in one place, and if so where?

**Comment by diegomura** [comment]
Just like the example. Call `Font.register` once somewhere before render the document. Should not only work the first time the doc is rendered, but the following times also. The cool part is that react-pdf caches the fonts, so the will only be processed the first time and then he will reuse them

**Comment by flaurida** [comment]
Awesome, will try it out! Is this released yet?

**Comment by diegomura** [comment]
No. I will today. It will be 0.7.1

**Comment by rogierslag** [comment]
Love it!

**Comment by flaurida** [comment]
Thank you!

**Comment by diegomura** [comment]
You're welcome! Sorry I didn't deploy it yesterday 😅

**Comment by flaurida** [comment]
no worries!

**Comment by flaurida** [comment]
Hi Diego,
Apparently the new version causes our build to fail with something to do with `yoga-layout`. Thoughts on how to fix?

```
Command: npm -- run autogypi && npm -- run build:node
Arguments: 
Directory: /home/circleci/repo/node_modules/yoga-layout
Output:
> yoga-layout@1.6.0 autogypi /home/circleci/repo/node_modules/yoga-layout
> autogypi


> yoga-layout@1.6.0 build:node /home/circleci/repo/node_modules/yoga-layout
> npm -- run copy-sources && npm -- run node-gyp configure build


> yoga-layout@1.6.0 copy-sources /home/circleci/repo/node_modules/yoga-layout
> ! npm -s -- run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)


> yoga-layout@1.6.0 node-gyp /home/circleci/repo/node_modules/yoga-layout
> node-gyp "configure" "build"

make: Entering directory '/home/circleci/repo/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CC(target) Release/obj.target/nbind/sources/yoga/YGNodeList.o
../sources/yoga/YGNodeList.c: In function ‘YGNodeListInsert’:
../sources/yoga/YGNodeList.c:67:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (uint32_t i = list->count; i > index; i--) {
   ^
../sources/yoga/YGNodeList.c:67:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
../sources/yoga/YGNodeList.c: In function ‘YGNodeListRemove’:
../sources/yoga/YGNodeList.c:79:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (uint32_t i = index; i < list->count - 1; i++) {
   ^
../sources/yoga/YGNodeList.c: In function ‘YGNodeListDelete’:
../sources/yoga/YGNodeList.c:89:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (uint32_t i = 0; i < list->count; i++) {
   ^
nbind.target.mk:134: recipe for target 'Release/obj.target/nbind/sources/yoga/YGNodeList.o' failed
make: Leaving directory '/home/circleci/repo/node_modules/yoga-layout/build'
make: *** [Release/obj.target/nbind/sources/yoga/YGNodeList.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-111-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/circleci/repo/node_modules/yoga-layout
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.6.0 node-gyp: `node-gyp "configure" "build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.6.0 node-gyp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-02-08T21_33_52_955Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.6.0 build:node: `npm -- run copy-sources && npm -- run node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.6.0 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-02-08T21_33_52_974Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

**Comment by diegomura** [comment]
hum... how? You upgraded from `0.7.0` to `0.7.1`?

**Pull request merged**
