### PR TITLE
Remove precompiled yoga

### LINKED ISSUE #144: invalid ELF header
Hi, i have an error when i run yarn example -- fractals
somebody know how to solve it?
Thanks.
> yarn example v0.20.3
> $ babel-node ./examples/index.js fractals
> Running the fractals example
> Error: /**/**/react-pdf/packages/react-pdf/bin/7/nbind.node: invalid ELF header
>     at Object.Module._extensions..node (module.js:598:18)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at initNode (/**/**/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:141:15)
>     at /**/**/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:115:13
>     at findCompiledModule (/**/**/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:79:13)
>     at find (/**/**/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:93:13)

### PR DESCRIPTION
**Pull request by langovoi**
This will fix #144, maybe #151, also allow usage of `react-pdf` not only with Node.js 6, 7 or 8.

**List of requirements if someone get error on Linux:**
- `g++-4.9` or newer;
- `-std=c99` flag in `CFLAGS`;

### CODE REVIEW

**Comment by diegomura** [comment]
This is how it was before #57 . You think this is not longer an issue?

**Comment by langovoi** [comment]
Also with if remove recompiled yoga-template and add some fixes to `react-pdf` and `react-pdf-dom` I got `examples/dom-bindings` works!

(I replaced example with code from `fractals` and add some fixes for webpack)
react_pdf_dom_bindings_2018-01-17_21-12-01

**Comment by jbovenschen** [comment]
This is really amazing! Thanks for looking into it. I think this is good to merge. Can you make a separate PR for the fixed DOM bindings?

**Comment by langovoi** [comment]
Sure, I will make separate PR for `dom` and `core` packages.

**Comment by diegomura** [comment]
@langovoi this is awesome!! Thanks so much for your contribution.
I agree with @jbovenschen about separating into two PRs both changes
Not sure why but MacOS build for node 6 is not running on Travis

**Comment by langovoi** [comment]
Travis have a troubles last 48 hours which not fully resolved:
https://www.traviscistatus.com/incidents/c1s4dlyxd4lf
https://www.traviscistatus.com/incidents/p1g70p3qrq4z

**Comment by jbovenschen** [comment]
Seems like it isn't booting the linux image for now. Going to merge it.

**Comment by diegomura** [comment]
@jbovenschen I wanted to test it before merging it, but It's ok. I'm going to close the issues when I try it late today

**Comment by jbovenschen** [comment]
@diegomura I just tested it on my macbook and linux laptop, and it seems to work on both without having to doing a lot emscripten related stuff (What I did before). So I thought it was ok to merge.

**Comment by diegomura** [comment]
Was ok 😉  Thanks

**Pull request merged**
