### PR TITLE
schedulePassiveEffects is not a function

### PR DESCRIPTION
**Pull request by hutch120**
Essentially copied the fix from the [ink repo](https://github.com/vadimdemedes/ink/blob/d30e4c8f1a681d6620669eea81f680efede211a5/src/create-reconciler.js)

References:
https://github.com/diegomura/react-pdf/issues/557

### CODE REVIEW

**Comment by hutch120** [comment]
Not sure why the build is failing... the node_modules/scheduler/package.json I have in my dev is `"version": "0.13.6"` I can't tell which version is used by the build process. 

I noticed this in yarn.lock
```
react-test-renderer@^16.0.0-0:
  version "16.8.3"
  resolved "https://registry.yarnpkg.com/react-test-renderer/-/react-test-renderer-16.8.3.tgz#230006af264cc46aeef94392e04747c21839e05e"
  integrity sha512-rjJGYebduKNZH0k1bUivVrRLX04JfIQ0FKJLPK10TAb06XWhfi4gTobooF9K/DEFNW98iGac3OSxkfIJUN9Mdg==
  dependencies:
    object-assign "^4.1.1"
    prop-types "^15.6.2"
    react-is "^16.8.3"
    scheduler "^0.13.3"
```

**Comment by diegomura** [comment]
Have you figure out why build is failing? (Sorry. On the phone right now so I cannot run any tests)

**Comment by hutch120** [comment]
@diegomura Looks like it might be something to do with the version of scheduler not having the functions unstable_scheduleCallback and unstable_cancelCallback. I added it to packages.json but now I get this error in the travis build log `The command "yarn --frozen-lockfile" failed and exited with 1 during .`

**Comment by hutch120** [comment]
@diegomura Hi, I followed the bouncing ball, so to speak, and had to remove the flag `--frozen-lockfile` to get the build to work. Hope that's ok.

**Pull request merged**
