### PR TITLE
fix: copy paste for registered font

### PR DESCRIPTION
**Pull request by chihyux**
Hello! Thank you for creating this package. My company has chosen this package, and I encountered an issue when using a custom font where copying text results in garbled characters. I have also noticed that there are many similar issues in the repository, where the characters copied from the generated PDF are different from what is displayed on the screen.

I have found that the package uses an older version of [pdfkit](https://github.com/foliojs/pdfkit), and based on the code in the latest version of that package, the following function is no longer used:
```
 this.unicode[gid] = this.font._cmapProcessor.codePointsForGlyph(
            glyph.id
          );
```
The reason for this change is that the function was producing duplicate Unicode values, leading to consecutive or incorrect characters in the cmap and resulting in garbled text when copying.

Additionally, when using this package in my country, which uses Chinese characters, copying text from the generated document in Chrome and Edge browsers can also result in garbled characters when there are a large number of Unicode characters. I suspect that this is because the original implementation `toUnicodeCmap` used `bfrange` for generating Unicode mappings for glyphs, and when there are many Unicode characters(more than 244 characters), the browser cannot correctly interpret the corresponding Unicode values. To address this issue, I suggest changing the cmap implementation to use `bfchar`, which resolved the problem.

### CODE REVIEW

**Comment by santialbo** [comment]
Please @diegomura have a look at this PR if you have some time. This has been a very problematic issue for us :(

**Review by diegomura — APPROVED** [review]
Thanks! Looks good to me comparing to latest pdfkit.Will try to test it today and merge it

**Comment by teq-vunguyen** [comment]
@diegomura I also got this issue, waiting for next release 🙏🏻

**Comment by benrandja-akram** [comment]
@diegomura is there any chance this pr will be merged soon ?

**Comment by teq-vunguyen** [comment]
@chihyux I have used your PR and customized it into a separate node module, and it works 100%. I really appreciate that 💯

**Comment by hazem3500** [comment]
Was anyone able to monkey patch this with [patch-package](https://www.npmjs.com/package/patch-package) by any chance? 🤔 or deployed a forked package to NPM?

Found the code on the `node_modules` minified so would need some dissecting to patch 😅

**Comment by teq-vunguyen** [comment]
@hazem3500 I'm using patch-package, you should change only file **pdfkit.browser.es.js** in folder lib at pdfkit. Check this PR and replace that.

**Comment by sandeepdotcode** [comment]
@hazem3500 If you haven't already got it to work, I have it in `patches` folder in this [repo](https://github.com/sandeepdotcode/code-crafted-resume). You can just raw download the file and run patch-package.

Thanks for the code @chihyux !

**Comment by cupcakearmy** [comment]
We added the patch to our codebase, and all tests are running fine + we can now actually copy test. can confirm the fix works.

How to use the patch?

```bash
git clone git@github.com:chihyux/react-pdf.git
cd react-pdf
yarn
yarn build
tar -czvf renderer.tar.gz ./packages/renderer
```

Then simply create a tarball of the relevant packages. and -> `"@react-pdf/renderer": "./renderer.tar.gz"` in your package json.

Hope this gets merged soon :)

**Comment by teq-vunguyen** [comment]
I use the `patch-package` library to perform a find-and-replace operation, similar to the pull request mentioned above, in the file `node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js`. It is truly effective with a success rate of 100%. I don't know if there's anything wrong here 🤔 @hazem3500

**Comment by kaloyanBozhkov** [comment]
+1 waiting on this

**Comment by kaloyanBozhkov** [comment]
What was mentioned by @teq-vunguyen  worked for me as well. I had to[ do this](https://github.com/oven-sh/bun/issues/2336#issuecomment-1712458657) since bun was not happy with patch-package, but overall everything went good. Also thanks to  @sandeepdotcode's [patch]([patch-package](https://www.npmjs.com/package/patch-package)).

Let's get this merged! Probably many resume websites are having issues due to this 🤯

**Comment by Elelan** [comment]
When will this be merged?

**Comment by kaloyanBozhkov** [comment]
Let's merge this bad boy

**Comment by diegomura** [comment]
Changes merged in https://github.com/diegomura/react-pdf/pull/2488

Sorry guys, specially @chihyux, messed up this PR branch when rebasing and testing changes. All looked good. Thanks so much for the contribution!

**Pull request closed without merging**
