### PR TITLE
feat: add fallback font support

### PR DESCRIPTION
**Pull request by nikgraf**
Allows to add multiple fallback fonts and will fall back to the next font and eventually last font in case the glyph is not available.

I added an example for testing:

Screenshot 2024-02-14 at 17 31 59

Happy to update the PR in case something is missing e.g. test. Just need to know what and where.

### CODE REVIEW

**Comment by hendrikmolder** [comment]
Looking forward to getting this merged! 🚀

**Comment by nikgraf** [comment]
hey @diegomura, wanted to ping and ask if this is what you expected here https://github.com/diegomura/react-pdf/pull/1833#issuecomment-1937052590

**Comment by Linkerbrain** [comment]
This would be really useful to be merged !

**Comment by hendrikmolder** [comment]
@nikgraf Should we also update the types package to allow an array of strings for `fontFamily`?

**Comment by nikgraf** [comment]
@hendrikmolder definitely, will do as soon as there is any sign that the author is interested to merge it

**Comment by diegomura** [comment]
Hi @nikgraf ! Thanks for working on this and sorry for the silence. Not usually easy to find the time unfortunately. If you can submit the types update I promise I'll review this in a timely manner.

**Comment by nikgraf** [comment]
@diegomura types are updated, I force pushed my branch

**Comment by diegomura** [comment]
Thanks!!

**Comment by nikgraf** [comment]
Thank you @diegomura! This is such a fantastic library. Great job!

**Comment by hendrikmolder** [comment]
Hey, realised we didn't bump the types package – https://github.com/diegomura/react-pdf/pull/2723

**Pull request merged**
