### PR TITLE
Svg support

### LINKED ISSUE #29: Gain compatibility with react-primitives-svg
Gain compatibility with [react-primitives-svg](https://github.com/chengyin/react-primitives-svg).

### PR DESCRIPTION
**Pull request by diegomura**
WIP of adding SVG support to react-pdf.

Ultimately this will be hosted in a separate npm package so we don't force everyone to download more dependencies, but I'm open to hear thoughts about it.

Fixes #29

### CODE REVIEW

**Comment by DuncanMacWeb** [comment]
How about using Rollup’s [code-splitting and dynamic loading](https://levelup.gitconnected.com/code-splitting-for-libraries-bundling-for-npm-with-rollup-1-0-2522c7437697) to avoid unnecessary downloads in the browser? We also need to render GIFs with react-pdf, which might be quite hefty, and it would be nice if it “just worked” for users, without adding unnecessary excess weight.

**Comment by diegomura** [comment]
Thanks. I’ll check that out. It’s unclear how that could work because all elements have the same entry’s point (/section/elements/index) but I’ll read that article and see what I can do. I won’t be on my computer until the afternoon but I promise I’ll answer everything then!

**Comment by DuncanMacWeb** [comment]
I think it relies on using async imports to import the modules you need just-in-time, so it would rely on being able to render asynchronously.

**Comment by diegomura** [comment]
I read the article you shared and it talks about how to split the build in different bundles (which is great!) but I cannot see yet how the dynamic import would be.

The solution you propose involves building the `Svg` and `SvgNode` classes separately in a different bundle, which I agree it can be a good idea. But I don't know yet how async import would work then. I would appreciate some guidance on this subject. If you can't don't worry. I'll run some more tests then and try to figure it out, but it may take longer

**Comment by jcteague** [comment]
Will this accept a string as the svg content?  We are using a charting library that creates the svg, and currently using svg-to-pdfkit to render it in the document.

**Comment by DuncanMacWeb** [comment]
@diegomura There’s [a link](https://rollupjs.org/repl?shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBEWU5BTUlDJTIwSU1QT1JUUyU1Q24lMjAlMjAlMjBSb2xsdXAlMjBzdXBwb3J0cyUyMGF1dG9tYXRpYyUyMGNodW5raW5nJTIwYW5kJTIwbGF6eS1sb2FkaW5nJTVDbiUyMCUyMCUyMHZpYSUyMGR5bmFtaWMlMjBpbXBvcnRzJTIwdXRpbGl6aW5nJTIwdGhlJTIwaW1wb3J0JTIwbWVjaGFuaXNtJTVDbiUyMCUyMCUyMG9mJTIwdGhlJTIwaG9zdCUyMHN5c3RlbS4lMjAqJTJGJTVDbmlmJTIwKGRpc3BsYXlNYXRoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KCcuJTJGbWF0aHMuanMnKS50aGVuKGZ1bmN0aW9uJTIwKG1hdGhzKSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKG1hdGhzLnNxdWFyZSg1KSklM0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lNUN0JTdEKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBzcXVhcmUlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoeCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHNxdWFyZSh4KSUyMColMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzcXVhcmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0ElMjIwMCUyMiU3RA==) at the bottom of the article with an example of dynamic imports, which Rollup translates into references to the chunks from code-splitting.

**Comment by diegomura** [comment]
@jcteague for the moment this only supports svg primitives as react-pdf objects. However, it's on the scope to support `.svg` files. Having the svg loaded as a string should be pretty straightforward once we have that done, since would be also reading the svg content and creating appropriate inner instances

**Comment by diegomura** [comment]
Thanks @DuncanMacWeb! That was very helpful. Are you sure that adding dynamic imports wouldn't break some people projects? It's kind of magical how it works, and I never used it before in a third-party library.

The ideal solution would be to dynamically import `Svg` and `SvgNode` in the [createInstance method](https://github.com/diegomura/react-pdf/pull/506/files#diff-b1b689b044676be036d134b9dada443fR32) when some if these elements are present in the tree. However, this is not possible since this method cannot be `async` (it's being used by the renderer itself, that runs synchronously) 

The only alternative I see so far would be only dynamically import `@react-pdf/svgkit` on render time (that is an async process) and use it then. I think that would do the trick, since it's truly the heavy part on this process.

However, I have another question: wouldn't this break any future effort on making the render process non-blocking (#464)? A dynamic import will make the worker script not pure, causing to fail isn't it?

Thanks for your help in this area!

**Comment by kristianstroka** [comment]
Any news about this pull request?

**Comment by Hathoriel** [comment]
Any news? Could someone please fix this failed tests?

**Comment by andrioid** [comment]
Why was this closed? Was it too hard to integrate, or is it being reworked into the next version?

**Comment by diegomura** [comment]
It's already done in the next version!

**Comment by RodionCoach** [comment]
does have official documentation smth info about Svg?

**Comment by oeed** [comment]
@RodionCoach and for anyone a little confused, he was referring to version 2 which you can find here: https://github.com/diegomura/react-pdf/tree/v2

**Comment by izzybaer** [comment]
@diegomura is there SVG support in v2? and if so - when will v2 be out of beta?

**Comment by jsaelhof** [comment]
@diegomura I installed react-pdf as normal and it pulled this version in my package.json: "@react-pdf/renderer": "^2.0.0-beta.6". I am able to import {Svg} from "@react-pdf/renderer". For the life of me I can't figure out what the expected syntax to use is. Are there any docs or could drop a quick reply here? I'm trying something like this but i don't see the svg (the debug _does_ appear so i know it's outputting _something_):
```
<Document>
      <Page size="A4" style={styles.page}>
        <View>
          <Svg
            debug={true}
            src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTMsMTRMMy41LDE0LjA3TDguMDcsOS41QzcuODksOC44NSA4LjA2LDguMTEgOC41OSw3LjU5QzkuMzcsNi44IDEwLjYzLDYuOCAxMS40MSw3LjU5QzExLjk0LDguMTEgMTIuMTEsOC44NSAxMS45Myw5LjVMMTQuNSwxMi4wN0wxNSwxMkMxNS4xOCwxMiAxNS4zNSwxMiAxNS41LDEyLjA3TDE5LjA3LDguNUMxOSw4LjM1IDE5LDguMTggMTksOEEyLDIgMCAwLDEgMjEsNkEyLDIgMCAwLDEgMjMsOEEyLDIgMCAwLDEgMjEsMTBDMjAuODIsMTAgMjAuNjUsMTAgMjAuNSw5LjkzTDE2LjkzLDEzLjVDMTcsMTMuNjUgMTcsMTMuODIgMTcsMTRBMiwyIDAgMCwxIDE1LDE2QTIsMiAwIDAsMSAxMywxNEwxMy4wNywxMy41TDEwLjUsMTAuOTNDMTAuMTgsMTEgOS44MiwxMSA5LjUsMTAuOTNMNC45MywxNS41TDUsMTZBMiwyIDAgMCwxIDMsMThBMiwyIDAgMCwxIDEsMTZBMiwyIDAgMCwxIDMsMTRaIiAvPjwvc3ZnPg=="
      />
    </View>
   <View style={styles.section}>
      <Text>Section #1</Text>
    </View>
  </Page>
</Document>
```

**Comment by joerglehmann** [comment]
@jsaelhof 

> For the life of me I can't figure out what the expected syntax to use is.

I think, `<Svg />` should be used like the actual `<svg />` tag (with the react-specific attribute notation, so `stroke-width` becomes `strokeWidth`, etc)..

This syntax works for me:

```js
import { Svg, G, Line, Circle, Polyline } from "@react-pdf/renderer"
```

```jsx
<Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 247.06813 247.06813">
  <G fill="none" stroke="#000" strokeMiterlimit={10} strokeWidth={6}>
    <Circle cx="123" cy="123" r="120" />
    <Line x1="180.65817" y1="123.5932" x2="66.52024" y2="123.5932" />
    <Polyline points="117.248 168.634 66.52 123.593 117.307 78.428" />
  </G>
</Svg>
```

Hope this helps!

**Comment by luskin** [comment]
@joerglehmann How did you get this working? I am on `2.0.0-beta.14` and when testing your code I receive the following error:

`Module '"@react-pdf/renderer"' has no exported member 'Svg'. Did you mean to use 'import Svg from "@react-pdf/renderer"' instead? `

**Comment by joerglehmann** [comment]
> @joerglehmann How did you get this working? I am on `2.0.0-beta.14` and when testing your code I receive the following error:
> 
> `Module '"@react-pdf/renderer"' has no exported member 'Svg'. Did you mean to use 'import Svg from "@react-pdf/renderer"' instead? `

@luskin My example worked in 2.0.0-beta.6, and it seems that the package structure has changed since then (Svg elements seem to have moved from `@react-pdf/renderer` to `@react-pdf/primitives`)

**Pull request closed without merging**
