### PR TITLE
V2 description fix

### LINKED ISSUE #1616: Descriptions in package.json
**Describe the bug**

some packages in monorepo don't have description, so npm and all other tools use readme 
for description that starts with svg image

**Screenshots**

Снимок экрана 2021-11-25 в 14 02 16

Снимок экрана 2021-11-25 в 14 01 07

**Expected behavior**
package.json have clear and concise description of what package does.

### PR DESCRIPTION
**Pull request by rjsduf0503**
Hello @jeetiss !

Sorry, I deleted our branch so PR was closed.. 
So we send new PR in modified version in your advice!

Thanks for your preparing "good first issues" for us.
We found #1616 issue's bugs are appear in 8 packages and those were render, type, primitives, stylesheet, render, font, layout, and image.
We added "clear and concise" descriptions of what package does as much as possible in package.json file in some repositories.
So we could fix #1616 issue!
We wanted to add fixed image, but in our opinion, the BundlePhobia site seemed to be modified only when it was merged.

If our fixes are wrong, please leave a comment.

Thank you for reading this commit and your attention for us. Have a great day!!! 🙂

Desktop
- OS : Windows 10
- Browser : Chrome
- React-pdf version : 2.0.0

### CODE REVIEW

**Review by jeetiss — CHANGES_REQUESTED** [review]
Could you please revert all these changes in all `yarn.lock`?)

**Comment by rjsduf0503** [comment]
Hi @jeetiss !
We revert all these changes in yarn.lock just few minutes ago!
Thanks for your attention for us!
Have a nice day :)

**Comment by rjsduf0503** [comment]
And so on, can we get a new "good first issue"?
If you can give us a new "good first issue", we'll feel very grateful.
Thanks!!!!!!!!!!!!!!

**Comment by jeetiss** [comment]
@rjsduf0503 thanks, i'm going to merge this tomorrow

check the new issues in https://github.com/diegomura/react-pdf/discussions/1615 🙌🏻
if you have any questions you're welcome!

**Comment by rjsduf0503** [comment]
@jeetiss thanks!!!! we'll start as soon as possible that new issue!
Can you merge this PR please? :)

**Review by jeetiss — APPROVED** [review]

**Comment by rjsduf0503** [comment]
@jeetiss you're welcome!!
You don't have to mind at all.
Thank you for merging this PR :)

**Pull request merged**
