### PR TITLE
add type for order css property

### PR DESCRIPTION
**Pull request by davbrito**

### CODE REVIEW

**Review by diegomura — APPROVED** [review]

**Comment by jeetiss** [comment]
@diegomura `yoga` doesn't support order property so this PR doesn't make any sense

**Comment by diegomura** [comment]
Oh I thought it did. I'll revert it. Thanks!

**Comment by davbrito** [comment]
> @diegomura `yoga` doesn't support order property so this PR doesn't make any sense

[React PDF documentation](https://react-pdf.org/styling#:~:text=justifyContent-,order,-Layout)  points that it's a valid CSS property. I have used it and it works perfectly.

**Comment by jeetiss** [comment]
you can use the CSS property `order` but it doesn't do anything!
[👉🏻 repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a788912608004e4a305805c300130c55eaa80150c28d80462a01e83cbd89fd740c3535a9430d8d24cd2dacec61bd9d5d02d81dfcd382fca3c33474f5a2a1444ce2ac6dec00185382b20199333cd8430af2b4a28d8ac563cdcb13925d6a9b8800591a825ac23929fd7805c3fce8199959d80801b8c8c94121618c2070600194ba308e002c3030a165802c307930f024391455ec5f34001c78949490c07c37080bef63a801580034d3180fcfe00be00085d05010231ec0036284c2e1ff40400252c480017b80a03c11183b19455343541b2d800941ec028170680031593dcc0093c15110a874160fcc406500000)

the previous issue https://github.com/diegomura/react-pdf/issues/1340

**Comment by diegomura** [comment]
I don't remember why order is in the docs 😅  I thought we were ordering elements in the layout phase but couldn't find where.

**Pull request merged**
