### PR TITLE
Updating README.md Document && Added Locally Runnable Examples (incl. boilerplate template)

### PR DESCRIPTION
**Pull request by davidlee0602**
Hello,

I would like to make a contribution to make the README.md document more attractive to new users. In addition, showcase and display use cases available through the package.

Changes Suggested / Made in PR:
1. I have included a brief introductory message about the package.
2. I have added and linked in README.md the rendered PDF samples already available in the ./packages/examples folder.
3. I have added locally runnable boilerplate templates based on samples already available in ./packages/examples.
[The boilerplate templates are available under "./packages/templates".

Please kindly review and advise if the PR is feasible. Thank you so much!

### CODE REVIEW

**Comment by diegomura** [comment]
Hi @davidlee0602 ! Thanks so much for taking the time to contribute to this project.
Sorry, but can you explain a bit more what's the purpose of the `template` package and it's difference with the `examples` one? I think it's important to keep the amount of packages as low as possible in general. I'm not closed to adding new ones of course! But would like to understand the purpose of this one better 😄

**Comment by davidlee0602** [comment]
Hello @diegomura !

Thank you for spending time to review my pull request :).
I definitely agree with you that the "examples" (./packages/examples) package should suffice, and the "templates" (./packages/examples/templates - in the PR) package may be considered redundant 😄.

However, I personally tried to run the "examples" package (node ./packages/examples/src/index.js) after installing all dependencies via (./packages/examples/package.json) to run locally on my machine, however, I was unable to do so without running into problems. 

Without the setup instructions for the examples package, I was unable to run locally due to the fact that 1. I may be lacking knowledge and/or 2. unfamiliar with setting up additional packages to get the package started 😢 . 

I was personally thinking that a simpler setup with instructions like:
" (Example)
To check the source code and run the examples locally:
(Done via your OS terminal)
1. Clone this repository with your terminal: git clone https://github.com/diegomura/react-pdf
2. Navigate to sub-directory "/react-pdf/templates/"
3. Navigate to folder: Fractal, Resume, or Document.
4. In the folder of the template to view, enter the command in the terminal: npm install --legacy-peer-deps
5. After all dependencies are installed, type in terminal to run: npm start
6. Sample pages will be viewable through the browser @ http://localhost:3000/
"
Would help newcomers run the examples package with fewer obstacles.

Please kindly advise.

Thank you!!!!

**Comment by diegomura** [comment]
Hey! thanks for answering. 100% agree we should make newcomers easier to onboard on the project. I think the examples project is not working, not your fault that didn't run. To be honest, I thought nobody will run it, but rather just look at the examples doc code. But I was clearly wrong 😄 I think it's a good idea to make it work thought, and not just use it as an examples folder but also for dev purposes. However, creating a new `templates` package is not the way to go imo. Would be better to just fix examples

**Comment by davidlee0602** [comment]
I will attempt to create another PR in the future to try to see if the the already existing examples package can be made to run! :) thank you!

**Comment by erik-stephens** [comment]
As someone evaluating different pdf libraries/tools, I can say that this is exactly what I was looking for.  I wonder if `s/templates/examples/` is all that is needed to make this more acceptable (ie no extra package).

**Pull request closed without merging**
