### PR TITLE
feat: add bidi support

### PR DESCRIPTION
**Pull request by ahmed-novalabs**
- Adds RTL support. Trying to finish the work in #1485.
 Related To/ Should fix:
	-  #1571 
	-  #1636
	- #933
	-  #960
	- #1394
	- #747
	- #856
- ~~Adds basic font fallback support.~~
Let me know what I can change and add, there is still work to be done.

### CODE REVIEW

**Comment by diegomura** [comment]
Thanks @ahmed-novalabs ! What's left to do yet?

**Comment by benshabatnoam** [comment]
@ahmed-novalabs is this going to resolve #960 as well?

**Comment by ahmed-novalabs** [comment]
> Thanks @ahmed-novalabs ! What's left to do yet?

The font fallback isn't well-implemented and has some bugs, I didn't add any tests for bidi or the font fallback.
There is also an issue with copying, it seems to copy the text in reverse, and I am not sure how to approach fixing that (Might be related to this mozilla/pdf.js#2141).

> @ahmed-novalabs is this going to resolve #960 as well?

Yes, it should.

Any feedback would be appreciated.

**Comment by ahmed-novalabs** [comment]
I removed the font fallback code since it was done in a primitive way, If I get the time, I will work on another PR for that

**Comment by diegomura** [comment]
Thanks @ahmed-novalabs !! This is awesome. Can you provider a test plan for this PR so I can check it. I scanned the code and looks good. I'll find some time to review it more carefully once I can have a test plan 😄

**Comment by ahmed-novalabs** [comment]
@diegomura I don't have a lot of experience with testing, so I am not sure how to make or approach making a test plan. If you can provide an example or a guide of what you expect, I can work on it.

**Comment by diegomura** [comment]
@ahmed-novalabs but how did you do to code this? By test plan all I mean is a way to see it working and understand how it works

**Comment by benshabatnoam** [comment]
> @ahmed-novalabs but how did you do to code this? By test plan all I mean is a way to see it working and understand how it works

@ahmed-novalabs I can help testing this if you guys need help with that.
Can I clone your code, build it, and use the bundle files to replace the npm package, to test this?

**Comment by ahmed-novalabs** [comment]
@benshabatnoam yes you can. You can follow the [contributing guide](https://github.com/diegomura/react-pdf/blob/master/.github/CONTRIBUTING.md#set-up-your-development-environment) on how to set it up. No extra steps were necessary for me.

**Comment by ahmed-novalabs** [comment]
> @ahmed-novalabs but how did you do to code this? By test plan all I mean is a way to see it working and understand how it works

Sorry I was busy last week, let me explain what I did. 
There are three main components
- The bidi engine, which calculates the bidi level and adds it as an attribute to the `attributedString`, which was already set up In your PR.
- [Mirroring characters](https://github.com/ahmed-novalabs/react-pdf/blob/e7cc4e6227f682644f761d726364a069ecc732fb/packages/textkit/src/layout/bidiMirroring.js#L21) based on it's bidi level. i.e. `(` becomes `)` in rtl.
- [Reordering characters](https://github.com/ahmed-novalabs/react-pdf/blob/e7cc4e6227f682644f761d726364a069ecc732fb/packages/textkit/src/layout/bidiReordering.js#L68) based on the bidi level, which has two main parts
	- Loop over every character in the run adding it to the array based on the order supplied by the bidi algorithm.
	- Ignore any ligature that was repeated by the bidi algorithm. 

### Things to test
- LTR languages should work exactly as they did before
- RTL languages should be rendered in the correct visual order ( right to left and top to bottom)
- Nested RTL in LTR and nested LTR in RTL should work exactly as they work in HTML.
- Some characters should be mirrored correctly in RTL context. i.e. `(` `[` `"` 
- Numbers should render in the correct visual order in RTL
- Any [ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)) should only be displayed once and be combined correctly.
- [Bidi unicode characters](https://www.w3.org/International/questions/qa-bidi-unicode-controls#basedirection) should correctly change the direction of text.

I have mainly tested with Arabic as that's what I can read. So I am not sure how it will fare with Hebrew and Farsi, everything should work correctly though.

**Comment by JasonMan34** [comment]
@diegomura What else is left to be done for the PR to enter? I'm OOTL as for what needs to be done / what's already been done and would like to help

**Comment by benshabatnoam** [comment]
> @benshabatnoam yes you can. You can follow the [contributing guide](https://github.com/diegomura/react-pdf/blob/master/.github/CONTRIBUTING.md#set-up-your-development-environment) on how to set it up. No extra steps were necessary for me.

Thank you @ahmed-novalabs I was able to use the contribution guide very easily just like you said.

I have tested your PR in Hebrew and I can confirm the check marked ones (the other I didn't check...):
- [ ] LTR languages should work exactly as they did before
- [x] RTL languages should be rendered in the correct visual order ( right to left and top to bottom)
- [ ] Nested RTL in LTR and nested LTR in RTL should work exactly as they work in HTML.
- [x] Some characters should be mirrored correctly in the RTL context. i.e. ( [ "
- [x] Numbers should render in the correct visual order in RTL
- [ ] Any ligatures should only be displayed once and be combined correctly.
- [ ] Bidi Unicode characters should correctly change the direction of the text.

I did find two problem:
- [ ] Dot char (.) is rendered at row start instead of row end
- [ ] Colon char (:) is rendered at row start instead of row end

Thanks for you time @ahmed-novalabs and if you need me to test further just ask.

**Comment by RotemZohar** [comment]
Any news on this? I'd really like to use this framework but BIDI support is a must for me.
Is there anything I can do to help approve the PR?

**Comment by benshabatnoam** [comment]
@ahmed-novalabs we didn't hear from you for quite some time, it felt like this PR is going on the right track to get merged 😞

**Comment by smahmood22** [comment]
any update on the RTL direction for this library?

**Comment by diegomura** [comment]
Sorry, couldn't test this. I see it has collected some conflicts, and @benshabatnoam findings haven't been fixed. I'd love this feature to land but it isn't ready as far as I see

**Comment by ahmedwalid05** [comment]
Hello, 
I am sorry for taking this long to reply, I am in between changing jobs right now, so I have some time to work on this. 
Also, I don't have access to the `ahmed-novalabs` account anymore. So I might have to close this PR and create another one.

@benshabatnoam 
Thank you for going through my PR and testing. 
I checked the use case you tested, and if I understood you correctly, I believe it's working correctly according to the bidi algorithm.
image
renders as
image

If you want the bracket to be in the correct place, you have to explicitly define the direction of that text block, using the style attribute `direction='ltr'` or `direction='rtl'`.  That behavior matches that of HTML with the `dir` attribute. You can check out [this sandbox ](https://codesandbox.io/s/sweet-bas-xlf0bl?file=/index.html) for an example.


What is missing from this PR is [`dir='auto'`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir#:~:text=auto%2C%20which%20lets%20the%20user%20agent%20decide.%20It%20uses%20a%20basic%20algorithm%20as%20it%20parses%20the%20characters%20inside%20the%20element%20until%20it%20finds%20a%20character%20with%20a%20strong%20directionality%2C%20then%20applies%20that%20directionality%20to%20the%20whole%20element.), which decides the direction based on the first non-weak character (e.g. not punctuation). I am not sure if that would easy to implement, but if that's required for the PR to be merged, I can look more into it.

**Comment by jerrydixon1** [comment]
@ahmedwalid05 Any traction on this? It would be crucial for what my company is trying to do with PDFs in regard to RTL language support. Is there any way I could help?

**Comment by shrey-sachdeva-shipsy** [comment]
@ahmedwalid05 I tried using the fix branch as a package. The fix breaks on `packages/textkit/src/layout/bidiReordering.js` line 80, where a null check is missing on `glyph`. I believe this is only happening in some cases where ligature is present, but haven't been able to identify a pattern. Otherwise, it does solve the core issue.

@diegomura @ahmedwalid05 Would be great if we could land this in production, please let me know if I can help in any way.

**Comment by danielagam** [comment]
For Hebrew (And also another languages..) all you need to do is to add a supported font like in the example below and register the font:




Good luck!

**Comment by ilyas-ascend** [comment]
Any update on this PR?
When this will be pushed to production?

**Comment by darrynten** [comment]
Will this fix incorrect rendering of Vietnamese characters like Đ ?

**Comment by VladyslavKondratiev** [comment]
hi, guys!
I'm also looking for RTL support.. could you, please, share the status?

**Comment by Levis92** [comment]
Any updates on this? At this rate we need to change library if we can't expect this feature to be added any time soon.

**Comment by TheMikeyRoss** [comment]
Any updates on this one?

**Comment by Kluckmuck** [comment]
any progress? Would love to have this

**Comment by TheMikeyRoss** [comment]
@diegomura

**Pull request closed without merging**
