### PR TITLE
Update Resume Text and Use .map for Rendering ExperienceEntry Components

### PR DESCRIPTION
**Pull request by mattstates**
I made some spelling changes to fit with the theme for this mock resume. I also extracted the ExperienceEntry prop info into an array of objects and used .map to to render the components.

### CODE REVIEW

**Comment by mattstates** [comment]
As a Star Wars fan and someone looking to make more open source contributions, I thought I could help out here. Please let me know if I need to address anything. Thanks!

**Comment by diegomura** [comment]
If you ever want to contribute to react-pdf just ping me that we might find something for you to do!

**Comment by mattstates** [comment]
Thanks Diego. I will let you know. I want to be careful about committing to more than I could deliver on.

**Comment by diegomura** [comment]
Makes sense. It's a clever thought haha. I've been in the other side and things can get stressful. Just let me know!

**Pull request merged**
