### PR TITLE
Add borders support

### LINKED ISSUE #127: Borders not being rendered?
Upon a cursory reading of the code I see that borders are supported. Do they only work on certain elements?
```
const CognitiveFunctionOverview = ({name}) => {
  const styles = StyleSheet.create({
    style: {
      paddingRight: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#CCCCCC'
    }
  });

  return (
  <View style={styles.style}>
    <Text>
      CF1 {name}
    </Text>
  </View>
  )
};
```
No border is displayed.

### LINKED ISSUE #133: Image examples are not working
Image used in the example doesn't exist anymore. Maybe examples could be updated.

### PR DESCRIPTION
**Pull request by diegomura**
Fixes #127 
Fixes #133

### CODE REVIEW

**Comment by KerenChandran** [comment]
Not sure if this was intended, but the borders are still not showing up for the other elements. I quickly looked into the code and it seems that drawBorders needs to be called on the other elements.

Not sure if you just forgot to add the call to the other elements, or if you had a different way to tackle the issue

**Comment by diegomura** [comment]
Damn. You're right. I'll fix it asap

**Comment by KerenChandran** [comment]
Thought you might be busy, so I just created the PR. Do you happen to have a roadmap for a 1.0 release?

**Comment by diegomura** [comment]
Thank you man! I really appreciate it.
I don't have a fixed roadmap, but I think the two bigger issues we are having right now are:

- Yoga does not build in Linux (#57)
- Pdfkit not working in the browser (#101)

Once we have these two working, I will feel very confident on releasing the 1.0 😄

**Comment by jmjpro** [comment]
I see the 1.0.0 milestone here: https://github.com/diegomura/react-pdf/milestone/1

Thanks for looking into this @KerenChandran. I was tackling the same problem just yesterday. I tried manually adding `this.drawBorders()` in the View component as you did I still didn't see any borders in the output. Do you have a working example?

**Comment by diegomura** [comment]
@jmjpro yes. But the last two points can wait. Would be great to have them, but not it's mandatory. Feel free to contribute on the one you feel more comfortable 😄

**Comment by KerenChandran** [comment]
@jmjpro @diegomura 

Something really odd is happening. On version 0.4.3, the borders still do not render. However, for my resume project (which I set to version 0.4.2 locally), if I apply `this.drawBorders()` change directly in `node_modules/@react-pdf/core/lib/elements/View.js`, the borders render as expected.

I'm going to spend the rest of today trying to understand what's going on and will report back my findings. I tested that on node 8, so not sure if there is some weird behaviour for node 8 vs node 7. Also the changes I made in 0.4.3 are not present in the build output, so something might be wrong with the build output or my last commit.

**Pull request merged**
