### PR TITLE
Docs for Express usage

### PR DESCRIPTION
**Pull request by jb-reefer**
Added a section on how to send a PDF response with Express

### CODE REVIEW

**Comment by zenininja** [comment]
It is just 2 steps,
1. Get a PDF stream const pdfStream = ReactPDF.renderToStream(...)
2. Pipe the stream to response. fileStream.pipe(response); With appropriate content type etc...
`  response.setHeader('Content-Type', 'application/pdf');
  const contentDisposition = `attachment; filename=${fileName}`;
  response.setHeader('Content-Disposition', contentDisposition);
  fileStream.pipe(response);`

Hope this helps..

**Comment by jb-reefer** [comment]
Can we get this merged?

**Comment by diegomura** [comment]
I would be happy to add it to the docs https://github.com/react-pdf/site
Can you add it there? thanks!

**Comment by jb-reefer** [comment]
Made a PR on https://github.com/react-pdf/site/pull/46, closing this one

**Pull request closed without merging**
