### PR TITLE
Fixed `.yml` build error caused by ternary in script name for `e2e-node`

### PR DESCRIPTION
**Pull request by joelybahh**
Screenshot 2024-03-27 at 11 20 19 am
In response to the above error, which seems to have been triggered after my recent PR merge, I removed the ternary from the name. At a glance, this appears to be for vanity purposes anyway.

### CODE REVIEW

**Comment by joelybahh** [comment]
I thought this was a simple change because of small syntax error, looks like a can of worms I wasn't ready for 😅

**Comment by joelybahh** [comment]
Could the E2E tests output be different now that this.bits is correctly being set?

**Comment by ranma42** [comment]
> Could the E2E tests output be different now that this.bits is correctly being set?

That does not seem to be the cause, as there are no images involved in the test.
Additionally, in my environment the same diff is also detected running the tests on 6ffd1b96f5962f7abfb2e19d6249f1b5b519477e (right before the JPEG change). Finally, the very same issue seems to be present since the very beginning of the e2e tests 021c354ab834cfef30c3a95a618017f1d626ab87.

The difference seems to be in the encoding of the deflated stream (deflating the streams in reference.pdf and the test output using qpdf results in identical files, excepts for the "moving parts").

**Comment by wojtekmaj** [comment]
Duplicate of #2633

**Pull request closed without merging**
