### PR TITLE
fix: fetch assets in dynamic content (#1369, #1587, #1630, #1936, #2064)

### PR DESCRIPTION
**Pull request by mskec**
This PR fixes crashes with images inside dynamic content.

From looking at it, the problem was that assets weren't loaded for images inside dynamic content because `resolveAssets` was executed before `resolvePagination`. 
To resolve this, I've added `resolveAssets` as a step in relayout which forced me to add a bunch of async/await all over `resolvePagination`.

fixes: #1369, #1587, #1630, #1936, #2064

### CODE REVIEW

**Comment by mskec** [comment]
Hi @jeetiss, what do you think about this PR? Do you want me to improve something?

**Comment by tigerza117** [comment]
Approve !

**Comment by mskec** [comment]
Hi @jeetiss, @diegomura, it's been a couple of months since opening the PR without receiving any feedback.

Can you please take a look at it? Please let me know if you have some concerns on how it's implemented and maybe we can find another solution.

The PR is fixing a couple of issues that others have reported and they and me would love to have it merged.

**Comment by tigerza117** [comment]
@mskec I have some issue font load by fs not working in render function

**Pull request closed without merging**
