### PR TITLE
table component with react pdf

### PR DESCRIPTION
**Pull request by Bishwanath-Dey-Nayan**
I have worked on table component with the react-pdf library. I think that it will be helpfull for the developer who are actually working on this library. 
Please review the changes as i have created a new folder on the example folder named table.
I have added only the src folder of my project.For the full project please mail me 16103022@iubat.edu

### CODE REVIEW

**Comment by diegomura** [comment]
Hey @Bishwanath-Dey-Nayan !
Thanks for taking the time to add this 😄 

A couple of comments:

- Could you do it like the other examples are? I mean, your's is an entire web project. The other examples are done to run on your machine when you run `yarn example`.
- I feel the example is too specific. I think you can show the exact same thing with a more simple case and less lines

**Comment by Bishwanath-Dey-Nayan** [comment]
Thank you so much @diegomura for your review.
I will definitely work on the issue that you described on the comment and keep updating you.

**Comment by Misiu** [comment]
@Bishwanath-Dey-Nayan any updates on this? I'm new to react-pdf, but I'd like to add tables to some PDF's I want to generate, so YOur component will be very useful :)

**Comment by Bishwanath-Dey-Nayan** [comment]
> @Bishwanath-Dey-Nayan any updates on this? I'm new to react-pdf, but I'd like to add tables to some PDF's I want to generate, so YOur component will be very useful :)

Thanks for the appreciation @Misiu .But sorry to say there is no update on this as i became busy with another project.

**Pull request closed without merging**
