### PR TITLE
fix: CI workflow error & add separate reference files for different platforms

### PR DESCRIPTION
**Pull request by wojtekmaj**
Follow up after #2631 🫠

Fixes invalid syntax in workflow file.

Also, it turns out, generated PDFs differ slightly from platform to platform. As the previous reference file I generated comes from macOS, it fails when E2E is ran on linux. This fixes that by introducing platform-specific reference files.

### CODE REVIEW

**Review by diegomura — APPROVED** [review]
utACK

**Comment by diegomura** [comment]
@wojtekmaj looks good but tests are failing

**Comment by wojtekmaj** [comment]
I can actually reproduce that locally. jay-peg seemed to be released with the wrong configuration in package.json. Had to patch it up locally and forgot about it 🙈

**Comment by wojtekmaj** [comment]
You fixed that in https://github.com/diegomura/jay-peg/commit/d88f86c67ab2dd3569c4dc191243e791929bcdcc.

**Comment by wojtekmaj** [comment]
Dependency bumped in https://github.com/diegomura/react-pdf/pull/2635.

**Comment by wojtekmaj** [comment]
That's more like it

**Comment by wojtekmaj** [comment]
@diegomura Sorry for pinging you, but can we prioritize this PR? Having all the other PRs without CI running is affecting us quite badly 🙈

**Comment by coren-frankel** [comment]
It's been a while since @diegomura received a ping on this. 🙈 

If there is anything I can contribute, please let me know! I've found myself here a second time after following some held-up PRs that aim to solve issues I'm tracking.

**Pull request closed without merging**
