### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by DuncanMacWeb**
This would help with anything requiring up-to-date Rollup, for example, lazy-loading parts of react-pdf (like possibly SVG modules in #506, or if we ever should use WebAssembly as in [#364](https://github.com/diegomura/react-pdf/pull/364#issuecomment-436325980), as we would need to load either wasm or asm.js depending on the environment).

This includes swapping in `terser` in place of `uglify`, as uglify simply wasn’t compatible (I think with Babel’s output) any more, and [Webpack moved to terser by default as of November last year](https://twitter.com/wsokra/status/1064441984532848641).

### CODE REVIEW

**Comment by DuncanMacWeb** [comment]
I am seeing an error with this while packaging for the browser; just needs a bit more work to resolve:

```
./src/dom.js → dist/react-pdf.browser.cjs.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
[!] Error: 'default' is not exported by node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/dom.js (2:7)
1: /* eslint-disable no-unused-vars */
2: import React from 'react';
          ^
3:
4: import warning from '../src/utils/warning';
Error: 'default' is not exported by node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
    at error (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:14393:9)
    at handleMissingExport (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:14063:21)
    at Module.traceVariable (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:14494:17)
    at ModuleScope.findVariable (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:13369:37)
    at FunctionScope.ChildScope.findVariable (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:4218:67)
    at ChildScope.findVariable (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:4218:67)
    at Identifier.bind (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:11184:40)
    at CallExpression.NodeBase.bind (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:10214:23)
    at CallExpression.bind (/Users/mackenzied/dev/sciencedirect/react-pdf/node_modules/rollup/dist/rollup.js:11296:31)
```

**Comment by DuncanMacWeb** [comment]
I am seeing an error with this while packaging for the browser; just needs a bit more work to resolve:

```
./src/dom.js → dist/react-pdf.browser.cjs.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
[!] Error: 'default' is not exported by node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/dom.js (2:7)
1: /* eslint-disable no-unused-vars */
2: import React from 'react';
          ^
3:
4: import warning from '../src/utils/warning';
Error: 'default' is not exported by node_modules/@babel/runtime/helpers/objectWithoutPropertiesLoose.js
    at error (/react-pdf/node_modules/rollup/dist/rollup.js:3597:30)
    at Module.error (/react-pdf/node_modules/rollup/dist/rollup.js:14393:9)
    at handleMissingExport (/react-pdf/node_modules/rollup/dist/rollup.js:14063:21)
    at Module.traceVariable (/react-pdf/node_modules/rollup/dist/rollup.js:14494:17)
    at ModuleScope.findVariable (/react-pdf/node_modules/rollup/dist/rollup.js:13369:37)
    at FunctionScope.ChildScope.findVariable (/react-pdf/node_modules/rollup/dist/rollup.js:4218:67)
    at ChildScope.findVariable (/react-pdf/node_modules/rollup/dist/rollup.js:4218:67)
    at Identifier.bind (/react-pdf/node_modules/rollup/dist/rollup.js:11184:40)
    at CallExpression.NodeBase.bind (/react-pdf/node_modules/rollup/dist/rollup.js:10214:23)
    at CallExpression.bind (/react-pdf/node_modules/rollup/dist/rollup.js:11296:31)
```

**Comment by diegomura** [comment]
Thanks! I tried this once and I ran with issues too. There are also some rollup plugins we rely on that does not work with the lastest rollup version, such as `rollup-plugin-ignore` (at least when I tried it)

**Comment by diegomura** [comment]
This fixes that bundle error you reported. However, I have some comments about this I will like to check before merging anything:

- Bundles appear to be bigger now (have to double check though)
- I find the new rollup script a bit complicated to understand. I would like to refactor it a bit if you don't mind

**Comment by DuncanMacWeb** [comment]
Of course, refactor away :)

If bundle size increases, that would definitely be an issue, but hopefully it can be resolved by improving the options passed to Babel or Terser, for example.

**Comment by diegomura** [comment]
I think it's ready!

**Comment by diegomura** [comment]
Thanks @DuncanMacWeb ! You rock 🤘🏼

**Pull request merged**
