### PR TITLE
fix(Base): stylesheet import

### PR DESCRIPTION
**Pull request by theobat**
Tried to use the example in the 0.3.0 release and it's broken, here's a quickfix

### CODE REVIEW

**Comment by diegomura** [comment]
Thanks @theobat ! 
Can you provide what error do you have, and what command did you executed?

There is something odd with the case of the `stylesheet` folder. I have it all lowercase in my dev env, but it's capitalized on github. Your solution may solve this issue, but it should work as it is, so I'm think there might be something else that's broken.

**Comment by diegomura** [comment]
@theobat can you try running the examples again?
Please pull last updates from master before running the script.
They are working for me :)

**Comment by theobat** [comment]
> There is something odd with the case of the stylesheet folder. I have it all lowercase in my dev env, but it's capitalized on github. Your solution may solve this issue, but it should work as it is, so I'm think there might be something else that's broken.

So this PR actually puts everything under the PascalCase directory and removes the normal one, perhaps it should be the other way round.

The error was cannot find '../Stylesheet' in path-to-react-pdf-in-node_modules. The file was Base.js

> can you try running the examples again?

@diegomura, Sure

**Comment by theobat** [comment]
```
➜  react-pdf git:(upstream-master) yarn example -- text
yarn example v0.24.6
$ babel-node ./examples/index.js text
{ Error: Cannot find module './Stylesheet'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/theophile/Documents/project/pro/betondirect/new/react-pdf/packages/react-pdf/lib/index.js:11:19)
    at Module._compile (module.js:571:32)
    at loader (/home/theophile/Documents/project/pro/betondirect/new/react-pdf/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/theophile/Documents/project/pro/betondirect/new/react-pdf/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
Done in 2.53s.
```

**Comment by theobat** [comment]
ok I see, the culprit is [there](https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf/src/index.js#L5)

Gonna open a new PR for this, so that we keep your lower case change. Closing this one.

**Pull request closed without merging**
