### PR TITLE
Fix memory leak

### LINKED ISSUE #314: "Cannot enlarge memory arrays" error when document is big.
**OS:**
MacOS 10.13.6

**React-pdf version:**
1.0.0-alpha.17

**Description:**
Hello! I'm using react-pdf to generate payment reports for a website I'm working on. The reports can often get really big, 400+ pages long. But I can only generate about 450 pages on my machine. If I try to render more, it hangs and finally crashes with the following error:
```
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 134217728, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0
```

I'm rendering the pdf reports in browser with PDFViewer.

**How to replicate issue including code snippet (if applies):**

I made a reproducible demo here (almost same code as in pageWrap example but rendering the same Don Quijote page content 1600 times):
https://github.com/binchik/react-pdf-crash-example

It loads for about 5-10 minutes then crashes with the "Cannot enlarge memory arrays" error.

### LINKED ISSUE #590: toBuffer doesn't handle error in render()
`toBuffer` doesn't call `await` on render... thus any exception will be unhandled... such as "Font family not registered".

https://github.com/diegomura/react-pdf/blob/1bc45ae3da2740eb008df8b1486454cd0753fe65/src/index.js#L63

```js
{"level":30,"time":1556912171434,"msg":"unhandledRejection caught","pid":78,"hostname":"6f3e3bc080d6","name":"print-react","v":1}
{"level":60,"time":1556912171434,"msg":"error caused exit","pid":78,"hostname":"6f3e3bc080d6","name":"print-react","err":{"type":"Error","message":"Font family not registered: Open Sans. Please register it calling Font.register() method.","stack":"Error: Font family not registered: Open Sans. Please register it calling Font.register() method.\n    at getFont (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:2536:11)\n    at Object.load (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:2548:16)\n    at Document.loadFonts (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:3926:30)\n    at Document.loadAssets (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:3982:29)\n    at Document.render (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4039:18)\n    at Root.render (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:60:25)\n    at Object.toBuffer (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4318:15)\n    at renderToStream (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4352:23)\n    at Promise (/usr/src/app/src/print-react/publish.js:147:22)\n    at new Promise (<anonymous>)"},"v":1}

```

### PR DESCRIPTION
**Pull request by bhunjadi**
Memory fix implementation based on findings and discussion in issue #378.
This should not be seen as a definite solution, but it should be a place to start.

Each node has a cleanup function which performs two things:
1. calls `unsetMeasureFunc` - this solves the problem with leaked instances (Text, Image)
2. calls `Yoga.Node.destroy(this)` - after testing export of a larger document with 1000 images with the same `src` I always got the error "Cannot enlarge memory arrays" and adding `Yoga.Node.destroy` solved this error. This is something that happened in our app after generating around 70 pdfs (server side) with size of 15-20 pages. 

So it is possible this might fix #314. Also fixes #590

### Implementation
Idea is that on each `remove()` called from wrapping algorithm we clean the removed child.
And after rendering, root instance calls `cleanup()` on the children:
```
async render() {
    this.instance = new PDFDocument({ autoFirstPage: false });
    await this.document.render();
    **this.cleanup();**
    this.isDirty = false;
}
```

### CODE REVIEW

**Comment by bhunjadi** [comment]
Argh, thanks. 
Looks like permissions were changed because of samba mount.

**Comment by diegomura** [comment]
Awesome! Thank you very much! @n6g7 if you can test it that would be great. I'll try to test it today also 😄

**Comment by n6g7** [comment]
So this PR does fix the leak in [the reproduction gist](https://gist.github.com/n6g7/4d9d9af8eb5b943b61c89c1c6fa29a3b) but not in [my original project](https://github.com/n6g7/httpdf). 🤔
I might be overlooking something, I'll look into it more tomorrow.

**Comment by bhunjadi** [comment]
I tried with your project and to me it looks like it is ok.
I used `yarn dev`, generated 1 pdf (/demo), made a heapdump, then generated another 10 docs and then made a heapdump again. I see no leaks there regarding leaked Root, Text, View etc.

Could you post your heapdumps when you do the tests again? Thanks

**Comment by n6g7** [comment]
Yep you're right, it looks like it's working! :D
I actually was still using `@react-pdf/node` instead `@react-pdf/renderer` for some reason so was 
running unpatched code unknowingly.

**Comment by diegomura** [comment]
So, I tried this today (sorry for taking that much!) and I found issues when the document re renders based on a changing state:

Kapture 2019-05-11 at 16 05 03

This is a very simple app that renders an image and a counter (that increases when clicking the button). First renders work, but afterwards it doesn't and it breaks the layout process.

What we should do is only cleaning the [subpages](https://github.com/diegomura/react-pdf/pull/591/files#diff-76514a85d16a6c21824a4b486dce5ec4R187) nodes, not the children since these are reused on each render to calculate the next subpages. I tried this approach and fixed this. I'll push it here. Could you please try if the gist and your projects to see that the memory leak is still gone?

**Comment by n6g7** [comment]
Hey @diegomura, I applied your commit on both the gist and my project and the leak was back. :(

**Comment by diegomura** [comment]
@n6g7 got it. We should definitely cleanup children in node (since those nodes are also used once in that env), but not on the web. Will appreciate a lot if you can test again in the gist and your project!

**Comment by bhunjadi** [comment]
Looks to me that with latest commit everything is OK - no memory leak in the gist nor my project!

**Comment by n6g7** [comment]
Yes, same results here, no leak in gist or my project with this latest commit. :)
Well done!

**Comment by diegomura** [comment]
Thank you! Merging this now and I’ll publish a new version later

**Comment by ameya-synerzip** [comment]
This happening again on re-rendering the pdf I have.
I am not sure how the disposeOnUnmount works here.

**Pull request merged**
