### PR TITLE
Fixed issue with lerna

### LINKED ISSUE #76: External dependencies will not install
**What is the current behavior?**
I  installed yarn for the first time per brew on mac. When trying to yarn install this project it seems to freeze on installing external dependencies. Nothing is happening for a long time:
bildschirmfoto 2017-05-22 um 14 21 26

**What is the expected behavior?**
Finishing the installation.

**Please mention your node.js, yarn and operating system version.**
node.js 7.10.0
yarn 0.24.5
macOS Sierra 10.12.4

### PR DESCRIPTION
**Pull request by elpic**
Looks like the last release candidate of lerna is freezeing the screen
on the instalation process. Move to the previous versions seems to work
fine.

Fixes #76

### CODE REVIEW

**Comment by diegomura** [comment]
🤔 I think this didn't work right?

**Comment by elpic** [comment]
@diegomura tests fail because tests are not working correctly but lerna is working fine

**Comment by elpic** [comment]
There was an issue with a version on @react-pdf/dom

**Comment by diegomura** [comment]
Thanks @elpic !!!! Merging this

**Pull request merged**
