### PR TITLE
Use cross fetch

### PR DESCRIPTION
**Pull request by diegomura**
#481

### CODE REVIEW

**Comment by DuncanMacWeb** [comment]
@diegomura you [said](https://github.com/diegomura/react-pdf/issues/481#issuecomment-462532509):

> My only concern here is that `isomorphic-fetch` is a `fbjs` dependency, which is also a `react-reconciler` dependency. So there's no really a way of getting rid of `isomorphic-fetch` completely right? what do you think @DuncanMacWeb ?

Good spot! I compared [`isomorphic-fetch`](https://npm.anvaka.com/#/view/2d/isomorphic-fetch) with [`cross-fetch`](https://npm.anvaka.com/#/view/2d/cross-fetch) over at npm.anvaka.com and it appears that the browser-side dependency whatwg-fetch happens to be pinned at `whatwg-fetch@3.0.0` for both... at present. So _right now_ I think both libraries would resolve to `whatwg-fetch@3.0.0` in the browser, and there would be negligible additional weight. But in future, particularly if a new version of `whatwg-fetch` is released, that could change... worth keeping an eye on 🤔

**Comment by diegomura** [comment]
Thanks for your input and quick response @DuncanMacWeb !

Looking further to this issue, I realized that `fbjs` is no longer a dependency of `react-reconciler`. It was on the version we were using, but by just upgrading it we can completely get rid of `isomorphic-fetch` (plus some more changes fo remove `fbjs` as a `react-pdf` dependency).

In addition, _I think_ these changes will have a positive impact on `react-pdf` size itself, since before `node-fetch` required `iconv-lite`, and as you can see [here](https://bundlephobia.com/result?p=@react-pdf/renderer@1.3.0) it was a big part of this library size. I won't be sure if this is the case until I see the updated graph though 😅 .

**Comment by diegomura** [comment]
All tests are green, and I did several manual checks (all good). 
I will merge this PR and release a new patch version 😄

**Comment by bartzy** [comment]
@diegomura I'm still getting `iconv-lite` as a depedency because of `cross-fetch` that depends on `node-fetch`. Any idea if this was eventually added to a release?

**Pull request merged**
