### PR TITLE
Add borders for images, text and view elements

### LINKED ISSUE #127: Borders not being rendered?
Upon a cursory reading of the code I see that borders are supported. Do they only work on certain elements?
```
const CognitiveFunctionOverview = ({name}) => {
  const styles = StyleSheet.create({
    style: {
      paddingRight: 10,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: '#CCCCCC'
    }
  });

  return (
  <View style={styles.style}>
    <Text>
      CF1 {name}
    </Text>
  </View>
  )
};
```
No border is displayed.

### PR DESCRIPTION
**Pull request by KerenChandran**
Fixes #127 
Related to #132 

This PR calls `this.drawBorders()` for the following elements to draw their borders:
- Images
- Text
- View

I believe the Page element behaves differently, meaning additional logic is required to render the page. Would definitely love to continue contributing to this project!

### CODE REVIEW

**Comment by diegomura** [comment]
It seems the snapshots are still failing. Did you run again the tests? With which node version are you running `yarn test` ?

**Comment by KerenChandran** [comment]
@diegomura I did run yarn test and updated the snapshots in the second commit. I'm running node version 8, so let me downgrade to 7 to see if the tests still fail on this branch.

**Comment by diegomura** [comment]
Yeah. You just confirmed a suspicion I had about that. Don't know why but Node 8 generates a different snapshot. Do you mind updating the test running node 7 meanwhile?

**Comment by KerenChandran** [comment]
Apparently I didn't switch my node version from 8 to 7 when I ran the tests on node 7 😅
After running the tests in node 7, I was getting the same errors. Guess I'll have to stay on node 7. 😃

**Comment by diegomura** [comment]
Thanks! Will release a new version with this fix

**Comment by KerenChandran** [comment]
Hm... this is weird. Just installed the latest release (0.4.3) in my resume project, and I don't see my changes inside lib 😕

**Pull request merged**
