### PR TITLE
Fix types for @types/react@18

### PR DESCRIPTION
**Pull request by karlhorky**
Ref: https://github.com/diegomura/react-pdf/issues/1062#issuecomment-1092100093
Ref: https://github.com/eps1lon/types-react-codemod#implicit-children
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691

Found some time to take a look at the breakages with `@types/react@18`, and opened a PR to fix the types in the @react-pdf/renderer package: https://github.com/diegomura/react-pdf/pull/1798

However, this does not fix the other packages in the monorepo. And this may cause breakage for @types/react versions lower than 18.

cc @diegomura @jeetiss

Copying my comment here for visibility:

> Hm, but it fails with [`@types/react` v18](https://www.npmjs.com/package/@types/react), which was just published (because of [the breaking changes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210)):
> 
> ```
> Run yarn tsc
> yarn run v1.22.18
> $ /home/runner/work/project/node_modules/.bin/tsc
> Error: project/generatePdf.tsx(212,6): error TS2769: No overload matches this call.
>   Overload 1 of 2, '(props: DocumentProps | Readonly<DocumentProps>): Document', gave the following error.
>     Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Document> & Readonly<DocumentProps>'.
>   Overload 2 of 2, '(props: DocumentProps, context: any): Document', gave the following error.
>     Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Document> & Readonly<DocumentProps>'.
> Error: project/generatePdf.tsx(213,8): error TS2769: No overload matches this call.
>   Overload 1 of 2, '(props: PageProps | Readonly<PageProps>): Page', gave the following error.
>     Type '{ children: Element; size: "A4"; style: { fontFamily: string; fontSize: number; lineHeight: number; paddingTop: number; paddingBottom: number; paddingHorizontal: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>   Overload 2 of 2, '(props: PageProps, context: any): Page', gave the following error.
>     Type '{ children: Element; size: "A4"; style: { fontFamily: string; fontSize: number; lineHeight: number; paddingTop: number; paddingBottom: number; paddingHorizontal: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
> Error: packages/learn.upleveled.io-server/routes/studentAssessments/learningOutcomesPdf.tsx(259,12): error TS2769: No overload matches this call.
>   Overload 1 of 2, '(props: SVGProps | Readonly<SVGProps>): Svg', gave the following error.
>     Type '{ children: Element[]; style: { marginTop: number; marginBottom: number; }; width: string; height: string; viewBox: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Svg> & Readonly<SVGProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Svg> & Readonly<SVGProps>'.
>   Overload 2 of 2, '(props: SVGProps, context: any): Svg', gave the following error.
>     Type '{ children: Element[]; style: { marginTop: number; marginBottom: number; }; width: string; height: string; viewBox: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Svg> & Readonly<SVGProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Svg> & Readonly<SVGProps>'.
> Error: project/generatePdf.tsx(266,16): error TS2769: No overload matches this call.
>   Overload 1 of 2, '(props: LinearGradientProps | Readonly<LinearGradientProps>): LinearGradient', gave the following error.
>     Type '{ children: Element[]; id: string; x1: string; x2: string; y1: string; y2: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<LinearGradient> & Readonly<LinearGradientProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<LinearGradient> & Readonly<LinearGradientProps>'.
>   Overload 2 of 2, '(props: LinearGradientProps, context: any): LinearGradient', gave the following error.
>     Type '{ children: Element[]; id: string; x1: string; x2: string; y1: string; y2: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<LinearGradient> & Readonly<LinearGradientProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<LinearGradient> & Readonly<LinearGradientProps>'.
> Error: project/generatePdf.tsx(285,8): error TS2769: No overload matches this call.
>   Overload 1 of 2, '(props: PageProps | Readonly<PageProps>): Page', gave the following error.
>     Type '{ children: Element; size: "A4"; style: { fontFamily: string; fontSize: number; lineHeight: number; paddingTop: number; paddingBottom: number; paddingHorizontal: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>   Overload 2 of 2, '(props: PageProps, context: any): Page', gave the following error.
>     Type '{ children: Element; size: "A4"; style: { fontFamily: string; fontSize: number; lineHeight: number; paddingTop: number; paddingBottom: number; paddingHorizontal: number; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error: Process completed with exit code 2.
> ```

### CODE REVIEW

**Review by JMHero05 — APPROVED** [review]

**Comment by eizgg** [comment]
Hi guys, any update?

**Review by ejmudrak — APPROVED** [review]

**Review by guillaume-acard — APPROVED** [review]
I tested with the changes and works fine 👍

**Comment by leeroyrose** [comment]
Hey any updates on when this will get released?

**Comment by karlhorky** [comment]
@leeroyrose You'll have to ask @diegomura and @jeetiss, I don't have commit / publishing access.

**Comment by chathu-novade** [comment]
Any update on getting this merged?

**Comment by karlhorky** [comment]
@diegomura @jeetiss I saw that you released a new version `@react-pdf/renderer` 3.0.0. I guess the major version bump would have unfortunately been a good time to get this change in, in case it is a breaking change for anyone.

But would you do this in a minor instead?

**Comment by BarrieLAJ** [comment]
Please could you release this update because we are trying to use the SVG component but without the children props in the types we cannot build the project.

**Comment by antoineharel** [comment]
I ended up creating custom components while an official update is released. 
`PropsWithChildren` does the job here:

```tsx
import ReactPDF from '@react-pdf/renderer';
import { FC, PropsWithChildren } from 'react';

export const Svg: FC<PropsWithChildren<ReactPDF.SVGProps>> = ({ ...props }) => (
  <ReactPDF.Svg {...props} />
);
export const G: FC<PropsWithChildren<ReactPDF.GProps>> = ({ ...props }) => (
  <ReactPDF.G {...props} />
);
export const ClipPath: FC<PropsWithChildren<ReactPDF.ClipPathProps>> = ({
  ...props
}) => <ReactPDF.ClipPath {...props} />;
```

**Comment by yangricardo** [comment]
> I ended up creating custom components while an official update is released. `PropsWithChildren` does the job here:
> 
> ```tsx
> import ReactPDF from '@react-pdf/renderer';
> import { FC, PropsWithChildren } from 'react';
> 
> export const Svg: FC<PropsWithChildren<ReactPDF.SVGProps>> = ({ ...props }) => (
>   <ReactPDF.Svg {...props} />
> );
> export const G: FC<PropsWithChildren<ReactPDF.GProps>> = ({ ...props }) => (
>   <ReactPDF.G {...props} />
> );
> export const ClipPath: FC<PropsWithChildren<ReactPDF.ClipPathProps>> = ({
>   ...props
> }) => <ReactPDF.ClipPath {...props} />;
> ```

That really solved, thanks!!

**Comment by vieirai** [comment]
Any movement on this?

**Comment by Jonur** [comment]
Hi all, have we got any news on when this will be merged?

**Comment by diegomura** [comment]
Hi all. Sorry for the lack of response in here. Been very busy and also on vacations 😄 Code looks good, but this would break support for versions prior 18 as far as I can tell. I'm open to suggestions, but I would like to prevent that as much as possible.

**Comment by chathu-novade** [comment]
This is really issue with all of my projects and using ts-ignore in someplace to overcome these. Most of project are using recent version of react. Better to support the latest with new react-pdf versions

**Comment by diegomura** [comment]
@chathu-novade isn't that a bit subjective? Not all projects can afford upgrading react so easily. So bumping react-pdf to 18 without being backwards compatible will break it to many. Merging this will just mean switching the sub-group of users to which this lib will be broken

**Comment by chathu-novade** [comment]
I mean we can release with a major version with react 18 support. Like many other react related projects does. I'm open to other suggestions. There are lot of issues created asking for 18 support.

**Comment by chathu-novade** [comment]
For this PR I think react types needs to be updated to use this. Which also currently we have done since we had issues with old types with react-pdf/renderer with Typescript.

**Comment by diegomura** [comment]
Thanks for the feedback! @karlhorky can you share what those libs are? I'm curious how they handled that. This project is in the most part very React agnostic (except for the reconciler and types) so dropping support just to have those merged seems a bit overkill. I wonder if there's a way to (via a postinstall script maybe) toggle deps based on the targeted react version

**Comment by karlhorky** [comment]
One of them was Gatsby: https://v5.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-required-react-version-is-18

Can't remember the other one off the top of my head, but considering how large of a release v18 is, I would imagine there will be more than just one.

Another way of going about it (if backwards compatibility is very important to you) is that you could maintain two versions - `@react-pdf/renderer@3.x.x` for pre-v18 versions, `@react-pdf/renderer@>=4.0.0` for v18+.

Maintaining conditional types / scripts seems difficult to deal with / buggy to me, but that would also be an option.

**Comment by diegomura** [comment]
Thanks @karlhorky ! Both cases I think are still maintaining old versions, at least until  a certain window. Backwards compatibility is important, as I know for certain some projects and companies using this lib won't have react migration to easy to do. Maintaining 2 parallel versions is a good approach, but this project does not have the dev power gatsby or next has, that why I was curious how I can prevent that.

I'll research about prepare or postinstall scripts. Another alternative would be extracting everything that's React version specific (which is not much) to an internal package, and require users to install a specific version of it depending what react version they are targeting. We can default to latest React version always. This is technically branching versions, but in a smaller codebase

**Comment by karlhorky** [comment]
> Another alternative would be extracting everything that's React version specific (which is not much) to an internal package, and require users to install a specific version of it depending what react version they are targeting. We can default to latest React version always. This is technically branching versions, but in a smaller codebase

Oh interesting, that may be nicer / less moving parts than postinstall scripts or similar 👍

**Comment by karlhorky** [comment]
Thanks for the merge! I'll give it a try in `@react-pdf/rendere@3.1.0`.

**Comment by dimitur2204** [comment]
Solved a lot of problems!

**Comment by jeetiss** [comment]
@dimitur2204 thanks, i hope so

@karlhorky, try `@react-pdf/renderer@3.1.1` because `3.1.0` is broken 🥲

**Comment by karlhorky** [comment]
Tried out `@react-pdf/renderer@3.1.1` - it seems to be working, thanks!

**Pull request merged**
