### PR TITLE
Add support for TrueType Collection font

### PR DESCRIPTION
**Pull request by daihuaye**
Add postscriptName unique identify to identify the font inside TrueType Collection format, which is an extra parameter in FontKit to support TTC file type.

FYI, the test font is Noto Sans Regular from github: https://github.com/jenskutilek/free-fonts

Here is the create function in fontkit.cjs.js
image

Here is the for loop to go through font in TTC collection and get the font that matches the postscriptName.
image

### CODE REVIEW

**Comment by daihuaye** [comment]
@diegomura Please review the pull request. Thanks.

**Comment by daihuaye** [comment]
@diegomura Who will do the code review for the pull request?

**Comment by diegomura** [comment]
Did you tested this on a react-pdf example locally? I ask this because this projects uses it's own fork of `fontkit` and the fact that fontkit supports this format already, doesnt mean it will work for our fork

**Comment by daihuaye** [comment]
Do you want me share the project I tested with react-pdf? I could set it up. Let me know if you have a good place to start.

**Comment by daihuaye** [comment]
@diegomura I create a app with create-react-app and use the React-pdf example create a pdf. I copy the react-pdf.browser.es.js change over the react-pdf in node_module folder. The font.ttc is used from the test folder.

Here is the result:
image

**Comment by daihuaye** [comment]
@diegomura Here is the static app I hosted in aws, you could test it here: https://test-pdf-app.s3-us-west-2.amazonaws.com/index.html

**Pull request merged**
