### PR TITLE
Add skype links

### PR DESCRIPTION
**Pull request by kuzivany**
Allow links such as `skype:username`

### CODE REVIEW

**Comment by diegomura** [comment]
Thanks. First time I see a link such as that. I'll have to run some tests before merging

**Comment by kuzivany** [comment]
Learning never stops =D These types of links open the Skype app if it's installed

**Comment by diegomura** [comment]
Hey! sorry for not responding soon. It's been some crazy days. I was thinking... do you mind changing this to support any type of protocols? There are also `whatsapp://` or `twitter://` and stuff like that thay may work on PDFs also. Never tried it, but I guess that if `skype://` works those should also work

**Comment by kuzivany** [comment]
Hi,

I know what those days are like, haha.

I'm not sure whether `whatsapp://` or `twitter://` work, I've never used them myself but I could just make it pick up on a set of characters followed by the colon and foward slashes (`://`)

**Comment by kuzivany** [comment]
Instead, or in addition to creating a long regular expression containing different strings like you have here:

```javascript
const PROTOCOL_REGEXP = /^(http|https|ftp|ftps|mailto|skype)/i;
```

possibly consider creating a regex like:

```javascript
const PROTOCOL_REGEXP_GENERIC = /^([a-z]+\:\/\/)/i;
```

I think a bit of research into some popular protocols or app links would lead down the right path. I don't have time at the moment but this is what I'd look into. Hope it's helpful

**Comment by diegomura** [comment]
Yes! Exactly

**Pull request merged**
